//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MailWindowservice.DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_Personal_Details
    {
        public int Student_Id { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Gender { get; set; }
        public string Father_First_Name { get; set; }
        public string Father_Last_Name { get; set; }
        public string Mother_First_Name { get; set; }
        public string Mother_Last_Name { get; set; }
        public System.DateTime Date_Of_Birth { get; set; }
        public string Email_Id { get; set; }
        public long Student_Phone_No { get; set; }
        public long Father_Phone_No { get; set; }
        public string Father_Occupation { get; set; }
        public System.DateTime Created_time_stamp { get; set; }
        public System.DateTime Updated_time_stamp { get; set; }
        public bool Is_Deleted { get; set; }
        public string Roll_No { get; set; }
        public string Password { get; set; }
        public string Subject { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
    }
}
