// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace StaffManagement.Entity
{
    public partial class Student_Personal_Details
    {
        [Key]
        public int Student_Id { get; set; }
        [Required]
        [StringLength(20)]
        public string First_Name { get; set; }
        [Required]
        [StringLength(20)]
        public string Last_Name { get; set; }
        [Required]
        [StringLength(6)]
        public string Gender { get; set; }
        [Required]
        [StringLength(20)]
        public string Father_First_Name { get; set; }
        [Required]
        [StringLength(20)]
        public string Father_Last_Name { get; set; }
        [Required]
        [StringLength(20)]
        public string Mother_First_Name { get; set; }
        [Required]
        [StringLength(20)]
        public string Mother_Last_Name { get; set; }
        [Column(TypeName = "date")]
        public DateTime? Date_Of_Birth { get; set; }
        [Required]
        [StringLength(50)]
        public string Email_Id { get; set; }
        public long Student_Phone_No { get; set; }
        public long Father_Phone_No { get; set; }
        [Required]
        [StringLength(30)]
        public string Father_Occupation { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Created_time_stamp { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Updated_time_stamp { get; set; }
        public bool Is_Deleted { get; set; }
        [Required]
        [StringLength(10)]
        public string Roll_No { get; set; }
        [Required]
        [StringLength(50)]
        public string Password { get; set; }
        [StringLength(20)]
        public string Subject { get; set; }
        [Column(TypeName = "date")]
        public DateTime? DateTime { get; set; }
    }
}