// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace StaffManagement.Entity
{
    public partial class Student_Mark_Information
    {
        [Key]
        public int Student_Mark_Id { get; set; }
        [Required]
        [StringLength(20)]
        public string Roll_No { get; set; }
        [Required]
        [StringLength(50)]
        public string Name { get; set; }
        public int Tamil { get; set; }
        public int English { get; set; }
        public int Maths { get; set; }
        public int Science { get; set; }
        public int Social { get; set; }
        public int Total { get; set; }
        public double Average { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Created_time_stamp { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Updated_time_stamp { get; set; }
        public bool Is_Deleted { get; set; }
    }
}