//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MailWindowservice.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_Mark_Information
    {
        public int Student_Mark_Id { get; set; }
        public string Roll_No { get; set; }
        public string Name { get; set; }
        public int Tamil { get; set; }
        public int English { get; set; }
        public int Maths { get; set; }
        public int Science { get; set; }
        public int Social { get; set; }
        public int Total { get; set; }
        public double Average { get; set; }
        public System.DateTime Created_time_stamp { get; set; }
        public System.DateTime Updated_time_stamp { get; set; }
        public bool Is_Deleted { get; set; }
    }
}
